import type { Metadata } from "next";
import { Inter, Bangers } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const bangers = Bangers({ weight: "400", subsets: ["latin"], variable: "--font-bangers" });

export const metadata: Metadata = {
  title: "OpenTL Spider-Network",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${bangers.variable} web-pattern`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
